In [5]:
import numpy as np
import pandas as pd

In [6]:
data = pd.read_csv('../data/raw/Bengaluru_House_Data.csv')
data.head(3)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00

In [7]:
data.shape

(13320, 9)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [9]:
for column in data.columns:
  print(data[column].value_counts())
  print("*"*30)

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
******************************
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
15-Aug               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
******************************
location
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: count, Length: 1305, dtype: int64
******************************
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: count, dtype: int64
******************************
society
GrrvaGr    80
PrarePa    76
Sryalan    59
Prtates    59
GMown E    56
           ..
Amionce     1
JaghtDe     1
Jauraht     1
Brity U     1
RSntsAp     1
Name: count, Length: 2688, dtype: int64
******************************
total_sqft
1200    843
1100    221
1500    205
2400    196
600     180
       ...
3580      1
2461      1
1437      1
2155      1
4689      1
Name: count, Length: 2117, dtype: int64
******************************
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
13.0       3
11.0       3
16.0       2
27.0       1
40.0       1
15.0       1
14.0       1
18.0       1
Name: count, dtype: int64
******************************
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
******************************
price
75.00     310
65.00     302
55.00     275
60.00     270
45.00     240
         ...
351.00      1
54.10       1
80.64       1
32.73       1
488.00      1
Name: count, Length: 1994, dtype: int64
******************************

In [10]:
data.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [11]:
data.drop(columns=['area_type', 'availability', 'society', 'balcony'],inplace=True)

In [12]:
# filling missing values

In [13]:
data.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [15]:
data['location'].value_counts()

location
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: count, Length: 1305, dtype: int64

In [16]:
data['location'] = data['location'].fillna('Sarjapur Road')

In [17]:
data['size'].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [18]:
data['size'] = data['size'].fillna('2 BHK')

In [19]:
data['bath'].median()

np.float64(2.0)

In [20]:
data['bath'] = data['bath'].fillna(data['bath'].median())

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13320 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [22]:
# bedroom - bhk problem

In [23]:
# data['size'] is a Series (column), not a single string
# split() works only on one string at a time

In [24]:
# So what .str.split() does
# 👉 It tells pandas:
# “Apply split() to each value in the column”

In [25]:
data['bhk'] = data['size'].str.split().str.get(0).astype(int)

In [26]:
# data = data[data['bhk'] <= 20]
data[data['bhk'] > 20]

                       location        size total_sqft  bath  price  bhk
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  40.0  660.0   43

In [27]:
# solving range issue in sqft

In [28]:
data['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [29]:
def convertRange(x):
  temp = x.split('-')
  if len(temp) == 2:
    return (float(temp[0]) + float(temp[1]))/2
  try:
    return float(x)
  except:
    return None

In [30]:
data['total_sqft'] = data['total_sqft'].apply(convertRange)

In [31]:
data.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

In [32]:
# Price per Square feet

In [33]:
data['price_per_sqft'] = data['price'] * 100000 / data['total_sqft']

In [34]:
data['price_per_sqft']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sqft, Length: 13320, dtype: float64

In [35]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [36]:
# finding outliers in location
data['location'].value_counts()

location
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Uvce Layout                         1
Abshot Layout                       1
Name: count, Length: 1306, dtype: int64

In [37]:
data['location'] = data['location'].apply(lambda x: x.strip().lower())
location_count = data['location'].value_counts()

In [38]:
location_count

location
whitefield                 541
sarjapur  road             399
electronic city            304
kanakpura road             273
thanisandra                237
                          ...
rahat bagh                   1
brigade road                 1
nagarbhavi  bda complex      1
rajanna layout               1
abshot layout                1
Name: count, Length: 1284, dtype: int64

In [39]:
location_count_less_10 = location_count[location_count <= 10]
location_count_less_10

location
1st block koramangala      10
sector 1 hsr layout        10
gunjur palya               10
dodsworth layout           10
nagappa reddy layout       10
                           ..
rahat bagh                  1
brigade road                1
nagarbhavi  bda complex     1
rajanna layout              1
abshot layout               1
Name: count, Length: 1043, dtype: int64

In [40]:
data['location'] = data['location'].apply(lambda x: 'other' if x in location_count_less_10 else x)

In [41]:
data['location'].value_counts()

location
other                 2886
whitefield             541
sarjapur  road         399
electronic city        304
kanakpura road         273
                      ...
nehru nagar             11
banjara layout          11
lb shastri nagar        11
pattandur agrahara      11
narayanapura            11
Name: count, Length: 242, dtype: int64

In [42]:
# Outlier detection and removal

In [43]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [44]:
(data['total_sqft']/data['bhk']).describe()

count    13274.000000
mean       575.074878
std        388.205175
min          0.250000
25%        473.333333
50%        552.500000
75%        625.000000
max      26136.000000
dtype: float64

In [45]:
data = data[((data['total_sqft']/data['bhk']) >= 300)]
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  12530.000000  12530.000000  12530.000000  12530.000000    12530.000000
mean    1594.564544      2.559537    111.382401      2.650838     6303.979357
std     1261.271296      1.077938    152.077329      0.976678     4162.237981
min      300.000000      1.000000      8.440000      1.000000      267.829813
25%     1116.000000      2.000000     49.000000      2.000000     4210.526316
50%     1300.000000      2.000000     70.000000      3.000000     5294.117647
75%     1700.000000      3.000000    115.000000      3.000000     6916.666667
max    52272.000000     16.000000   3600.000000     16.000000   176470.588235

In [46]:
data.shape

(12530, 7)

In [47]:
data['price_per_sqft'].describe()

count     12530.000000
mean       6303.979357
std        4162.237981
min         267.829813
25%        4210.526316
50%        5294.117647
75%        6916.666667
max      176470.588235
Name: price_per_sqft, dtype: float64

In [48]:
def remove_sqrt_outliers(df):
    df_output = pd.DataFrame()

    for key, subdf in df.groupby('location'):
        m = subdf['price_per_sqft'].mean()
        st = subdf['price_per_sqft'].std()

        reduced_df = subdf[(subdf['price_per_sqft'] > (m - st)) & (subdf['price_per_sqft'] <= (m + st))]
        df_output = pd.concat([df_output, reduced_df], ignore_index = True)
    return df_output

data = remove_sqrt_outliers(data)
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  10350.000000  10350.000000  10350.000000  10350.000000    10350.000000
mean    1508.646058      2.472560     91.347418      2.575556     5660.751992
std      879.853598      0.980519     86.425645      0.898481     2271.111971
min      300.000000      1.000000     10.000000      1.000000     1250.000000
25%     1110.000000      2.000000     49.000000      2.000000     4239.794174
50%     1286.000000      2.000000     67.000000      2.000000     5175.519668
75%     1650.000000      3.000000    100.000000      3.000000     6431.808627
max    30400.000000     16.000000   2200.000000     16.000000    24509.803922

In [49]:
data.shape

(10350, 7)

In [50]:
def remove_bhk_outlier(df):
  exclude_indices = np.array([])
  for location, location_df in df.groupby('location'):
    bhk_stats = {}
    for bhk, bhk_df in location_df.groupby('bhk'):
      bhk_stats[bhk] = {
          'mean': np.mean(bhk_df['price_per_sqft']),
          'std' : np.std(bhk_df['price_per_sqft']),
          'count': bhk_df.shape[0]
      }
    for bhk, bhk_df in location_df.groupby('bhk'):
      stats = bhk_stats.get(bhk-1)
      if stats and stats['count'] > 5:
        exclude_indices = np.append(exclude_indices, bhk_df[bhk_df.price_per_sqft<(stats['mean'])].index.values)
  return df.drop(exclude_indices, axis='index')

In [51]:
data = remove_bhk_outlier(data)

In [52]:
data.shape

(7415, 7)

In [53]:
data

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,1st block jayanagar,4 BHK,2850.0,4.0,428.0,4,15017.543860
1,1st block jayanagar,3 BHK,1630.0,3.0,194.0,3,11901.840491
2,1st block jayanagar,3 BHK,1875.0,2.0,235.0,3,12533.333333
3,1st block jayanagar,3 BHK,1200.0,2.0,130.0,3,10833.333333
4,1st block jayanagar,2 BHK,1235.0,2.0,148.0,2,11983.805668
...,...,...,...,...,...,...,...
10339,yeshwanthpur,2 BHK,1195.0,2.0,100.0,2,8368.200837
10340,yeshwanthpur,3 BHK,1692.0,3.0,108.0,3,6382.978723
10342,yeshwanthpur,6 Bedroom,2500.0,5.0,185.0,6,7400.000000
10347,yeshwanthpur,3 BHK,1855.0,3.0,135.0,3,7277.628032
10348,yeshwanthpur,3 BHK,1876.0,3.0,160.0,3,8528.784648

In [54]:
data.drop(columns=['size', 'price_per_sqft'], inplace=True)

In [55]:
# cleaned data

In [56]:
data.head()

              location  total_sqft  bath  price  bhk
0  1st block jayanagar      2850.0   4.0  428.0    4
1  1st block jayanagar      1630.0   3.0  194.0    3
2  1st block jayanagar      1875.0   2.0  235.0    3
3  1st block jayanagar      1200.0   2.0  130.0    3
4  1st block jayanagar      1235.0   2.0  148.0    2

In [57]:
data.to_csv("Cleaned_data.csv")

In [58]:
X = data.drop(columns=['price'])
y = data['price']

In [59]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [60]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [61]:
print(X_train.shape)
print(X_test.shape)

(5932, 4)
(1483, 4)

In [62]:
# applying linear Regression

In [63]:
column_trans = make_column_transformer((OneHotEncoder(sparse_output=False), ['location']),
                                       remainder='passthrough')

In [64]:
scaler = StandardScaler()

In [65]:
lr = LinearRegression()

In [66]:
pipe = make_pipeline(column_trans, scaler, lr)

In [67]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [68]:
y_pred_lr = pipe.predict(X_test)

In [69]:
r2_score(y_test, y_pred_lr)

0.8569517172904645

In [70]:
# applying lasso

In [71]:
lasso = Lasso()

In [72]:
pipe = make_pipeline(column_trans, scaler, lasso)

In [73]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [74]:
y_pred_lasso = pipe.predict(X_test)
r2_score(y_test, y_pred_lasso)

0.8468077870198838

In [75]:
# applying ridge

In [76]:
ridge = Ridge()

In [77]:
pipe = make_pipeline(column_trans, scaler, ridge)

In [78]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('ridge', Ridge())])

In [79]:
y_pred_ridge = pipe.predict(X_test)
r2_score(y_test, y_pred_ridge)

0.8569583907456292

In [80]:
print("No Regularization: ", r2_score(y_test, y_pred_lr))
print("Lasso: ", r2_score(y_test, y_pred_lasso))
print("Ridge: ", r2_score(y_test, y_pred_ridge))

No Regularization:  0.8569517172904645
Lasso:  0.8468077870198838
Ridge:  0.8569583907456292

In [82]:
import pickle

pickle.dump(pipe, open('../model/model.pkl', 'wb'))